# -*- coding: utf-8 -*-
"""Capstone_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtcCQvPJaCgY-pBNWJlJ4liZcsr-D1rU
"""

# data loader require for the transformer model

!git clone https://github.com/spencerbraun/anomaly_transformer_pytorch.git

# Commented out IPython magic to ensure Python compatibility.
# %cd anomaly_transformer_pytorch

# !pip install numpy pandas scikit-learn matplotlib tqdm pyyaml hydra-core torch

import numpy as np
import pandas as pd
import torch
import sklearn
print("All good")

import pandas as pd

df = pd.read_csv("/content/0.csv", sep=";")
df.columns = df.columns.str.strip()

# print(df.head())
# print(df.columns.tolist())
# print(df.shape)

from google.colab import drive
drive.mount('/content/drive')

# df.info()
# df.isnull().sum()

# print(df.columns.tolist())

feature_cols = [c for c in df.columns if c not in ["datetime", "anomaly"]]
X = df[feature_cols]
y = df["anomaly"]

feature_cols = [
    "Accelerometer1RMS",
    "Accelerometer2RMS",
    "Current",
    "Pressure",
    "Temperature",
    "Thermocouple",
    "Voltage",
    "Volume Flow RateRMS"
]

label_col = "anomaly"

from sklearn.preprocessing import StandardScaler

X = df[feature_cols].values
y = df[label_col].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import numpy as np

def create_sequences(X, y, seq_len=30):
    xs, ys = [], []
    for i in range(len(X) - seq_len + 1):
        x_seq = X[i:i+seq_len]
        y_seq = y[i:i+seq_len]
        xs.append(x_seq)
        ys.append(int(y_seq.max()))   # sequence is anomalous if any point is anomalous
    return np.array(xs), np.array(ys)

seq_len = 30
X_seq, y_seq = create_sequences(X_scaled, y, seq_len=seq_len)

print("X_seq shape:", X_seq.shape)   # (num_sequences, seq_len, num_features)
print("y_seq shape:", y_seq.shape)

import sys
sys.path.append('/content/anomaly_transformer_pytorch')

from model import AnomalyTransformer

import importlib
import model
importlib.reload(model)

from model import AnomalyTransformer
import torch

device = torch.device("cpu")   # 👈 use CPU first (avoid GPU bugs)

model = AnomalyTransformer(
    N=30,
    d_model=X_seq.shape[2],
    layers=3,
    lambda_=0.1
)

model = model.to(device)
model.eval()

# weights_path = "/content/drive/MyDrive/your_folder/anomaly_transformer_weights.pt"

# state_dict = torch.load(weights_path, map_location=device)
# model.load_state_dict(state_dict)

model.eval()

"""# check the file (on left side) -> anomaly_transformer_pytorch → model.py and replace the code below.
def gaussian_kernel(mean, sigma):
    sigma = sigma + 1e-6
    pi = torch.tensor(math.pi, device=sigma.device, dtype=sigma.dtype)
    normalize = 1 / (torch.sqrt(2 * pi) * sigma)
    return normalize * torch.exp(-0.5 * (mean / sigma).pow(2))
"""

import numpy as np
import torch

device = torch.device("cpu")   # use CPU first for debugging
model = model.to(device)
model.eval()

all_seq_scores = []

with torch.no_grad():
    for i in range(len(X_seq)):
        x = torch.tensor(X_seq[i], dtype=torch.float32).to(device)   # NO unsqueeze

        # clear stored layer outputs before each forward pass
        model.P_layers = []
        model.S_layers = []

        _ = model(x)
        score = model.anomaly_score(x)

        all_seq_scores.append(score.detach().cpu().numpy())

all_seq_scores = np.array(all_seq_scores)
print(all_seq_scores.shape)

x = torch.tensor(X_seq[0], dtype=torch.float32).to(device)
model.P_layers = []
model.S_layers = []
out = model(x)
score = model.anomaly_score(x)

print("x shape:", x.shape)
print("out shape:", out.shape)
print("score shape:", score.shape)

import numpy as np
import torch

device = torch.device("cpu")
model = model.to(device)
model.eval()

all_seq_scores = []

with torch.no_grad():
    for i in range(len(X_seq)):
        x = torch.tensor(X_seq[i], dtype=torch.float32).to(device)

        model.P_layers = []
        model.S_layers = []

        _ = model(x)
        score = model.anomaly_score(x)

        all_seq_scores.append(score.detach().cpu().numpy())

all_seq_scores = np.array(all_seq_scores)
print("all_seq_scores shape:", all_seq_scores.shape)

seq_scores = all_seq_scores.max(axis=1)
print(seq_scores.shape)
print(seq_scores[:10])
seq_scores_mean = all_seq_scores.mean(axis=1)
print(seq_scores_mean.shape)
print(seq_scores_mean[:10])

threshold = np.percentile(seq_scores, 70)
# threshold = 0.5
# threshold = np.percentile(scores, 85)
y_pred = (seq_scores > threshold).astype(int)

print("threshold:", threshold)
print("y_pred shape:", y_pred.shape)

from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score

print("F1:", f1_score(y_seq, y_pred))
print("Precision:", precision_score(y_seq, y_pred))
print("Recall:", recall_score(y_seq, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_seq, y_pred))

print("\nClassification Report:")
print(classification_report(y_seq, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.plot(seq_scores, label="Sequence anomaly score")
plt.axhline(threshold, linestyle="--", label="Threshold")
plt.legend()
plt.title("Anomaly Scores by Sequence")
plt.xlabel("Sequence Index")
plt.ylabel("Score")
plt.show()



all_seq_scores = []

with torch.no_grad():
    for i in range(len(X_seq)):
        x = torch.tensor(X_seq[i], dtype=torch.float32).to(device)

        model.P_layers = []
        model.S_layers = []

        _ = model(x)
        score = model.anomaly_score(x)

        all_seq_scores.append(score.detach().cpu().numpy())

all_seq_scores = np.array(all_seq_scores)
print("all_seq_scores shape:", all_seq_scores.shape)

seq_scores = all_seq_scores.max(axis=1)
threshold = np.percentile(seq_scores, 95)
y_pred = (seq_scores > threshold).astype(int)

from sklearn.metrics import f1_score, precision_score, recall_score, confusion_matrix

print("F1:", f1_score(y_seq, y_pred))
print("Precision:", precision_score(y_seq, y_pred))
print("Recall:", recall_score(y_seq, y_pred))
print(confusion_matrix(y_seq, y_pred))

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))
plt.plot(seq_scores)
plt.axhline(threshold, linestyle="--")
plt.title("Sequence-level anomaly scores")
plt.show()

